### ISSUE TITLE
Read properties file only once for all reports

### ISSUE THREAD

**Issue by Martin1887** [aibasel/lab#121]
Fetchers with many executions and attributes can produce giant properties files. Read a properties file of this size can take around 1 minute, and this can suppose several hours when many plots are needed.

So, would be possible run a range of steps at once to read the properties file in memory only once?

The CLI interface could be something like
```sh
python fetcher.py 2-2000
```
This would dramatically reduce the total time of generating reports, since each plot takes around 2 seconds when the properties file is in memory.

Thanks!

**Comment by jendrikseipp** [comment]
Thanks for the idea! The approach of using one report per step is currently baked deeply into Lab. As such it will be quite difficult to do this for all kinds of reports. For your specific use case, however, you can consider copying the ScatterPlotReport class and instead of requiring that there's exactly one attribute and one pair of algorithms, loop over multiple of them.
